### ISSUE TITLE
Users can swipe on profiles corresponding to their sexual orientation on the main page

### ISSUE THREAD

**Issue by clairezhang03** [CS-130-Organization/CredibleCupid#17]
## User Story
As a user, I would like swipe on profiles on my feed so that I can see the people I can match to.
#1 
## Detailed Description
Parent: #1 

## Acceptance Criteria
- [] Given a straight man, then I want to see women on my feed.
- [] Given a straight woman, then I want to see men on my feed.
- [] Given a homosexual man, then I want to see men on my feed.
- [] Given a homosexual woman, then I want to see women on my feed
